package Subway;

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

import java.awt.*;

public class CoupledBreakdownGenerator extends ViewableDigraph {
    public static final String OUT_BREAKDOWN_PORT = "outBreakdown";

    private UniformRandom _breakdownLengthGenerator;
    private UniformRandom _timeBetweenBreakdownGenerator;

    public CoupledBreakdownGenerator(UniformRandom breakdownLengthGenerator,
                                     UniformRandom timeBetweenBreakdownGenerator) {
        super("Breakdown Generator");
        _breakdownLengthGenerator = breakdownLengthGenerator;
        _timeBetweenBreakdownGenerator = timeBetweenBreakdownGenerator;
        initialize();
    }

    public String register(Train t) {
        // Add couplings for a particular train
        RandomBreakdownGenerator breakdownGenerator =
                new RandomBreakdownGenerator(
                        _breakdownLengthGenerator,
                        _timeBetweenBreakdownGenerator,
                        t);
        add(breakdownGenerator);
        String outPortName = t.getName();
        addOutport(outPortName);
        addCoupling(breakdownGenerator, RandomBreakdownGenerator.OUT_BREAKDOWN_PORT, this, outPortName);
        return outPortName;
    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 332);
        ((ViewableComponent)withName("Breakdowns: B")).setPreferredLocation(new Point(48, 172));
        ((ViewableComponent)withName("Breakdowns: A")).setPreferredLocation(new Point(50, 50));
    }
}
