package Subway;

import java.util.Optional;
import java.util.Random;

public class ExpFrame4TrainsNoDelays extends BaseExpFrame {

    public ExpFrame4TrainsNoDelays(boolean logResults) {
        super("Experimental Frame 4 Trains No Delays");

        SubwaySystemLoopConfig config = createScarboroughLoop(4)
                .with($ -> {
                    $.random = new Random();
                    $.loopName = "ExpFrame4TrainsNoDelays";
                    $.loadingTimeDistribution = new UniformRandom($.random, 15.0/60.0, 195.0/60.0);
                    $.delayTimeDistribution = new UniformRandom($.random, 0.0, 0.0);
                    $.delayProbability = 0.0;
                    $.logResults = logResults;
                }).createSubwaySystemLoop();
        addSubwaySystemLoop(config);
    }

    public ExpFrame4TrainsNoDelays() {
        this(false);
    }
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1608, 824);
        ((ViewableComponent)withName("ExpFrame4TrainsNoDelays")).setPreferredLocation(new Point(999, 474));
        ((ViewableComponent)withName("Scheduler_ExpFrame4TrainsNoDelays")).setPreferredLocation(new Point(15, 25));
        ((ViewableComponent)withName("Transducer_ExpFrame4TrainsNoDelays")).setPreferredLocation(new Point(38, 196));
        ((ViewableComponent)withName("Trains")).setPreferredLocation(new Point(957, 43));
    }
}
