package Subway;

import view.modeling.ViewableComponent;

import java.awt.Dimension;
import java.awt.Point;
import java.util.*;

public class SimplExpFrame extends BaseExpFrame {

    public SimplExpFrame() {
        super("Simple Experimental Frame");

        SubwaySystemLoopConfig ssl = new SubwaySystemLoopConfig.Builder().with($ -> {
            $.loopName = "Scarborough East";
            // Define the track lengths from Kennedy to McCowan.
            // The last element is the long segment from McCowan to Kennedy
            $.trackLengths = new ArrayList<>(Arrays.asList(3, 4));
            System.out.println("trackLengths.size = " + $.trackLengths.size());

            // Found typical business day ridership here:
            // https://www1.toronto.ca/wps/portal/contentonly?vgnextoid=c077c316f16e8410VgnVCM10000071d60f89RCRD
            //
            // To compute rates below, take values from spreadsheet, divide riders over
            // 12 hours and then divide by 2 (since we have one 'station' per direction
            // for each stop)

            $.stationData = new Object[][]{
                    // Station Name, Passenger Creation Rate
                    {"Kennedy", 13 /* 17,969 */},
                    {"Lawrence East", 3 /* 4,326 */},
            };

            // Trains
            // Note: According to the wikipedia Line 3 pages, 6 four-car trains operate
            // on the route, though it is reduced to 5 for construction until 2018.
            // From here: https://en.wikipedia.org/wiki/S-series_(Toronto_subway) the
            // train capacity is 30 seated, 55 standing
            //
            // Add three trains for each direction

            $.trainGroupName = "East Trains";
            $.trainNames = new ArrayList<>(Arrays.asList("ET1"));
            $.trainPositions = new ArrayList<>(Arrays.asList(1));
            $.loadingTimeDistribution = new UniformRandom(15.0/60.0, 15.0/60.0);

            $.delayTimeDistribution = new UniformRandom(0.0, 0.0);
            $.delayProbability = 0.0;
            $.random = new Random();
        }).createSubwaySystemLoop();

        addSubwaySystemLoop(ssl);
        initialize();
    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView() {
        preferredSize = new Dimension(1100, 581);
        ((ViewableComponent) withName("Transducer")).setPreferredLocation(new Point(50, 50));
        ((ViewableComponent) withName("East Trains")).setPreferredLocation(new Point(593, 9));
        ((ViewableComponent) withName("Scheduler_ScarboroughEast")).setPreferredLocation(new Point(40, 109));
        ((ViewableComponent) withName("Scarborough East")).setPreferredLocation(new Point(0, 238));
    }
}
