package Subway;

// Example of the Coupled break down generator with trains

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

import java.awt.*;

public class SimpleCoupledBreakdownTrainExample extends ViewableDigraph {
    public SimpleCoupledBreakdownTrainExample() {
        super("Coupled Train Example");
        Train t1 = new Train("A");
        Train t2 = new Train("B");
        CoupledBreakdownGenerator cbg = new CoupledBreakdownGenerator(
                new UniformRandom(1, 3),
                new UniformRandom(2, 3));
        add(t1);
        add(t2);
        add(cbg);
        String portName1 = cbg.register(t1);
        String portName2 = cbg.register(t2);
        addCoupling(cbg, portName1, t1, Train.IN_BREAKDOWN_PORT);
        addCoupling(cbg, portName2, t2, Train.IN_BREAKDOWN_PORT);
        initialize();
    }
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1060, 532);
        ((ViewableComponent)withName("B")).setPreferredLocation(new Point(644, 257));
        ((ViewableComponent)withName("A")).setPreferredLocation(new Point(486, 59));
        ((ViewableComponent)withName("Breakdown Generator")).setPreferredLocation(new Point(62, 135));
    }
}
