package Subway;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

import java.awt.Dimension;
import java.awt.Point;
import java.util.*;

public class SubwayLoop extends ViewableDigraph {
	
	private CircularList<ViewableAtomic> subwayLoop;
	
	// Here we leave the tracks as an input already instantiated
	// rather than creating them locally.  This allows us to use
	// references to track instances, which effectively means
	// we can share track instances among multiple loops.
	public SubwayLoop(String name, ArrayList<TrackSection> trackSections, ArrayList<Station> stations) {
		
		super(name);
		
		// Add the inports
		addInport(Train.OUT_PASSENGER_UNLOAD_PORT);
		addInport(TrackSection.IN_ACQUIRE_PORT);
		addInport(TrackSection.IN_RELEASE_PORT);
		addInport(Transducer.OUT_STOP);
		
		// Add the outports
		addOutport(Train.IN_PASSENGER_LOAD_PORT);
		addOutport(TrackSection.OUT_ACQUIRE_PORT);
		addOutport(TrackSection.OUT_RELEASE_PORT);
		addOutport(Station.OUT_PASSENGERS_LEFT_WAITING_PORT);

		// Build the loop composed of stations and tracks.
		// We start with a station and end with a track.
		// It is assumed the final track links the final station
		// and the first station.
        assert stations.size() == trackSections.size();
        subwayLoop = new CircularList(stations.size() * 2);
        int stationIndex, trackIndex;
        Station currentStation;
        TrackSection currentTrack;
        for (int k = 0; k < trackSections.size(); k++) {
            stationIndex = 2 * k;
            trackIndex = 2 * k + 1;

            currentTrack = trackSections.get(k);
            currentStation = stations.get(k);

            subwayLoop.add(stationIndex, currentStation);
            subwayLoop.add(trackIndex, currentTrack);
			
			// Couple the inports
			addCoupling(this,Train.OUT_PASSENGER_UNLOAD_PORT,currentStation,Train.OUT_PASSENGER_UNLOAD_PORT);
			addCoupling(this,TrackSection.IN_ACQUIRE_PORT,currentTrack,TrackSection.IN_ACQUIRE_PORT);
			addCoupling(this,TrackSection.IN_RELEASE_PORT,currentTrack,TrackSection.IN_RELEASE_PORT);
			addCoupling(this,Transducer.OUT_STOP,currentStation,Transducer.OUT_STOP);
			
			// Couple the outports
			addCoupling(currentStation,Train.IN_PASSENGER_LOAD_PORT,this,Train.IN_PASSENGER_LOAD_PORT);
			addCoupling(currentTrack,TrackSection.OUT_ACQUIRE_PORT,this,TrackSection.OUT_ACQUIRE_PORT);
			addCoupling(currentTrack,TrackSection.OUT_RELEASE_PORT,this,TrackSection.OUT_RELEASE_PORT);
			addCoupling(currentStation,Station.OUT_PASSENGERS_LEFT_WAITING_PORT,this,Station.OUT_PASSENGERS_LEFT_WAITING_PORT);
			
			add(currentStation);
			add(currentTrack);
		}
		
		initialize();
		
	}
	
	public int size() {
		return this.subwayLoop.size();
	}
	
	public ViewableAtomic get(int index) {
		return this.subwayLoop.get(index);
	}
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1542, 332);
        ((ViewableComponent)withName("TrackSection: 1")).setPreferredLocation(new Point(631, 75));
        ((ViewableComponent)withName("McCowan")).setPreferredLocation(new Point(1019, 133));
        ((ViewableComponent)withName("TrackSection: 3")).setPreferredLocation(new Point(119, 66));
        ((ViewableComponent)withName("Scarborough Centre (East)")).setPreferredLocation(new Point(926, 260));
        ((ViewableComponent)withName("Ellesmere (West)")).setPreferredLocation(new Point(454, 26));
        ((ViewableComponent)withName("Midland (West)")).setPreferredLocation(new Point(679, 3));
        ((ViewableComponent)withName("Kennedy")).setPreferredLocation(new Point(-6, 139));
        ((ViewableComponent)withName("Lawrence East (West)")).setPreferredLocation(new Point(192, 2));
        ((ViewableComponent)withName("Midland (East)")).setPreferredLocation(new Point(679, 258));
        ((ViewableComponent)withName("TrackSection: 1")).setPreferredLocation(new Point(618, 207));
        ((ViewableComponent)withName("TrackSection: 2")).setPreferredLocation(new Point(343, 222));
        ((ViewableComponent)withName("TrackSection: 1")).setPreferredLocation(new Point(848, 210));
        ((ViewableComponent)withName("TrackSection: 1")).setPreferredLocation(new Point(1070, 198));
        ((ViewableComponent)withName("Lawrence East (East)")).setPreferredLocation(new Point(87, 257));
        ((ViewableComponent)withName("Scarborough Centre (West)")).setPreferredLocation(new Point(929, 4));
        ((ViewableComponent)withName("TrackSection: 1")).setPreferredLocation(new Point(849, 58));
        ((ViewableComponent)withName("Ellesmere (East)")).setPreferredLocation(new Point(460, 259));
        ((ViewableComponent)withName("TrackSection: 3")).setPreferredLocation(new Point(51, 199));
        ((ViewableComponent)withName("TrackSection: 1")).setPreferredLocation(new Point(1070, 69));
        ((ViewableComponent)withName("TrackSection: 2")).setPreferredLocation(new Point(371, 71));
    }
}
